# Generated by Django 5.1.6 on 2025-02-19 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/df6ndrlj2/image/upload/v1739969127/default_sklyca.png', max_length=255, verbose_name='image'),
        ),
    ]
